// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TarGestAPI.Infrastructure.Context;

#nullable disable

namespace TarGestAPI.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextApi))]
    [Migration("20260614040042_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TarGestAPI.Domain.Entities.Tasks", b =>
                {
                    b.Property<int>("idTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTask"));

                    b.Property<string>("descriptionTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timeStartTask")
                        .HasColumnType("datetime2");

                    b.Property<string>("titleTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTask");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
